#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#npm run lint:ts << проверка всех файлов
#npx lint-staged #<< проверка измененных файлов нужна либв lint-staged настрофка в package.json после scripts
#npm run lint:scss
#npm run test