name: build and test project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build:prod
        if: always()
      - name: check eslint
        run: npm run lint:ts
        if: always()
      - name: check stylelint
        run: npm run lint:scss
        if: always()
      - name: start testing
        run: npm run test
        if: always()
      - name: build storybook
        run: npm run storybook:build
      - name: ui testing
        run: npm run loki:ci

